name: board_buddy
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.0+22

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  gen_art_bg: ^0.5.1
  use_scramble: ^0.0.13
  shared_preferences: ^2.5.4
  intl: ^0.19.0
  url_launcher: ^6.3.2
  url_launcher_ios: ^6.3.6
  flutter_svg: ^2.2.3
  flutter_bloc: ^9.1.1
  flutter_popup: ^3.3.9
  wheel_chooser: ^1.1.2
  meta: ^1.16.0
  bloc: ^9.1.0
  sqflite: ^2.4.2
  path: ^1.9.1
  share_plus: ^12.0.1
  in_app_review: ^2.0.11
  wakelock_plus: ^1.4.0
  gaimon: ^1.4.1
  talker: ^5.1.9
  talker_bloc_logger: ^5.1.9
  talker_flutter: ^5.1.9
  upgrader: ^12.3.0
  not_static_icons: ^0.30.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1
  intl_translation: ^0.21.0
  build_runner: ^2.10.4

dependency_overrides:
  intl: 0.20.2

flutter_launcher_icons:
  android: "launcher_icon"
  image_path_ios: "assets/logo/logo.png"
  image_path_ios_dark_transparent: "assets/logo/logo-dark.png"
  remove_alpha_ios: true
  ios: true
  image_path: "assets/logo/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_foreground: "assets/logo/logo.png"
  adaptive_icon_background: "#ffffff"

flutter:

  uses-material-design: true

  fonts:
  - family: RobotoMono
    fonts:
      - asset: assets/fonts/roboto_mono.ttf
        weight: 400
      - asset: assets/fonts/roboto_mono_thin.ttf
        weight: 300


flutter_intl:
  enabled: true
